[project]
name = "anki-squared"
version = "0.2.0"
description = "Anki add-on that enhances card creation by integrating AI and external APIs to provide rich content for flashcards."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
