"""empty message

Revision ID: 2d11fd741190
Revises: 
Create Date: 2021-02-15 20:57:13.529437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d11fd741190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.String(length=200), nullable=True),
    sa.Column('is_include_recognition', sa.Boolean(), nullable=True),
    sa.Column('is_marked', sa.Boolean(), nullable=True),
    sa.Column('is_graduated', sa.Boolean(), nullable=True),
    sa.Column('word_type', sa.Enum('none', 'noun', 'adjective', 'verb'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_word'), 'note', ['word'], unique=True)
    op.create_table('pronunciation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathmp3', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciations_to_notes_table',
    sa.Column('pronunciation_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['pronunciation_id'], ['pronunciation.id'], ),
    sa.PrimaryKeyConstraint('pronunciation_id', 'note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronunciations_to_notes_table')
    op.drop_table('pronunciation')
    op.drop_index(op.f('ix_note_word'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
